### ISSUE TITLE
shinyreactlog v1.0 release checklist

### ISSUE THREAD

**Issue by jcheng5** [rstudio/reactlog#5]
## shiny
- [x] Changes to Shiny v1.2 released to CRAN
- [x] Merge reactlog branch into Shiny v1.3

## shinyreactlog
- [x] Create RC branch `v1.0-rc`
- [x] Version bump
- [x] Run Grunt (so that shinyreactlog.min.js gets updated version number)
- [x] NEWS is up to date
- [x] LICENSE is up to date
- [x] Final test pass 
- [x] All milestone issues/PRs closed
- [x] R CMD check --as-cran
- [x] Reverse dependency check
- [x] Submit to CRAN
- [x] When accepted on CRAN, tag commit with version, push tag
- [x] Draft blog post
- [x] Publish blog post
- [x] Community post
- [x] Announcement tweet

## shiny.rstudio.com
- [x] Merge article changes
